version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: control_Kaiten
    ports:
      - "8000:8000"
    configs:
      - config
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

configs:
  config:
    file: ./config.toml