[secret]
fernet_key = 'PgKi9XHK7409xmwvhpzZQfuO2yekPQxtjmocjI1e6Fo='
clientId = 'tododdler-user-6899c608-f6c3-4bb7-954b-af6c8c28314e'
clientSecret = 'gAAAAABnijYaisud67nWIgrizL57j2DrXuJ0RnU0rcUsdN29nTOWm_GbAySiXRxw5fj0DZDGL7w3KFZqd_OS5Xy_5llSuCwWo8THH9dekvIRRtj_y26pU-S-NCgEKAxuRbkLARV7iQfS'